In [1]:
import torch
import numpy as np

In [3]:
def sumproducts(x, y):
    """
    x is a 1-dimensional int numpy array.
    y is a 1-dimensional int numpy array.
    Return the sum of x[i] * y[j] for all pairs of indices i, j.

    >>> sumproducts(np.arange(3000), np.arange(3000))
    20236502250000

    """
    result = 0
    for i in range(len(x)):
        for j in range(len(y)):
            result += x[i] * y[j]
    return result

In [50]:
%%timeit
vectorize_sumproducts(np.arange(200), np.arange(100))

54.8 µs ± 922 ns per loop (mean ± std. dev. of 7 runs, 10000 loops each)


In [34]:
def vectorize_sumproducts(x, y):
#     x = np.arange(x)
#     y = np.arange(y)
#     result = sum(np.dot(x, y))
    
    return np.sum(x*y[: ,np.newaxis])

In [108]:
def slice_fixed_point(x, l, start_point):
    """
    x is a 3-dimensional int numpy array, (n, ). First dimension represent the number of instances in the array.
    Second dimension is variable, depending on the length of a given instance. Third dimension is fixed
    to the number of features extracted per utterance in an instance.
    l is an integer representing the length of the utterances that the final array should have.
    start_point is an integer representing the point at which the final utterance should start in.
    Return a 3-dimensional int numpy array of shape (n, l, -1)

    """
    try:
        return x[: , :, start_point:start_point+l]
    except IndexError:
        return x[:, :, -l:]

In [112]:
x = np.arange(150).reshape(6,5,5)
print(x)
slice_fixed_point(x, 8, 8)

[[[  0   1   2   3   4]
  [  5   6   7   8   9]
  [ 10  11  12  13  14]
  [ 15  16  17  18  19]
  [ 20  21  22  23  24]]

 [[ 25  26  27  28  29]
  [ 30  31  32  33  34]
  [ 35  36  37  38  39]
  [ 40  41  42  43  44]
  [ 45  46  47  48  49]]

 [[ 50  51  52  53  54]
  [ 55  56  57  58  59]
  [ 60  61  62  63  64]
  [ 65  66  67  68  69]
  [ 70  71  72  73  74]]

 [[ 75  76  77  78  79]
  [ 80  81  82  83  84]
  [ 85  86  87  88  89]
  [ 90  91  92  93  94]
  [ 95  96  97  98  99]]

 [[100 101 102 103 104]
  [105 106 107 108 109]
  [110 111 112 113 114]
  [115 116 117 118 119]
  [120 121 122 123 124]]

 [[125 126 127 128 129]
  [130 131 132 133 134]
  [135 136 137 138 139]
  [140 141 142 143 144]
  [145 146 147 148 149]]]


array([], shape=(6, 5, 0), dtype=int32)

In [114]:
def slice_random_point(x, l):
    """
    x is a 3-dimensional int numpy array, (n, ). First dimension represent the number of instances in the array.
    Second dimension is variable, depending on the length of a given instance. Third dimension is fixed
    to the number of features extracted per utterance in an instance.
    l is an integer representing the length of the utterances that the final array should be in.
    Return a 3-dimensional int numpy array of shape (n, l, -1)

    """
    randy = np.random.randint(0, len(x[2])-l)
    return x[:, :, randy:randy+l]

In [115]:
slice_random_point(x, 2)

array([[[  2,   3],
        [  7,   8],
        [ 12,  13],
        [ 17,  18],
        [ 22,  23]],

       [[ 27,  28],
        [ 32,  33],
        [ 37,  38],
        [ 42,  43],
        [ 47,  48]],

       [[ 52,  53],
        [ 57,  58],
        [ 62,  63],
        [ 67,  68],
        [ 72,  73]],

       [[ 77,  78],
        [ 82,  83],
        [ 87,  88],
        [ 92,  93],
        [ 97,  98]],

       [[102, 103],
        [107, 108],
        [112, 113],
        [117, 118],
        [122, 123]],

       [[127, 128],
        [132, 133],
        [137, 138],
        [142, 143],
        [147, 148]]])

In [162]:
def pad_pattern_end(x):
    """
    x is a 3-dimensional int numpy array, (n, ). First dimension represent the number of instances in the array.
    Second dimension is variable, depending on the length of a given instance. Third dimension is fixed
    to the number of features extracted per utterance in an instance.

    Return a 3-dimensional int numpy array.

    """
    max = len(x[2])
    return np.pad(x[1], (0, max-len(x[2])), 'symmetric')

In [184]:
pa = np.arange(40).reshape(8, 5)
te = torch.tensor(3)
def numpy2tensor(x):
    """
    x is an numpy nd-array. 

    Return a pytorch Tensor of the same shape containing the same data.
    """
    y = torch.from_numpy(x)
    return y
pa = numpy2tensor(pa)
pa

tensor([[ 0,  1,  2,  3,  4],
        [ 5,  6,  7,  8,  9],
        [10, 11, 12, 13, 14],
        [15, 16, 17, 18, 19],
        [20, 21, 22, 23, 24],
        [25, 26, 27, 28, 29],
        [30, 31, 32, 33, 34],
        [35, 36, 37, 38, 39]], dtype=torch.int32)

In [185]:
def tensor2numpy(x):
    return x.numpy()
tensor2numpy(pa)

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24],
       [25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34],
       [35, 36, 37, 38, 39]])

In [164]:
p = np.array([1,2,3,4,5,6,7,8,9])
pad_pattern_end()

array([55, 56, 57, 58, 59, 60, 61])

In [35]:
%timeit vectorize_sumproducts(np.arange(200), np.arange(100))

54.8 µs ± 510 ns per loop (mean ± std. dev. of 7 runs, 10000 loops each)


In [30]:
%timeit vectorize_sumproducts(np.arange(200), np.arange(100))

15.5 µs ± 833 ns per loop (mean ± std. dev. of 7 runs, 100000 loops each)


In [191]:
w = np.array([55, 56, 57, 58, 59, 60, 61])
w = torch.from_numpy(w)
w.clamp(min=56)

tensor([56, 56, 57, 58, 59, 60, 61], dtype=torch.int32)

In [194]:
w.clamp(min=57, max=58)

tensor([57, 57, 57, 58, 58, 58, 58], dtype=torch.int32)

In [201]:
start = torch.arange(1.,5.)
stop = torch.empty(4).fill_(10)
torch.lerp(start, stop, 0.9)

tensor([9.1000, 9.2000, 9.3000, 9.4000])

In [222]:
def tensor_sumproducts(x,y):
    """
    x is an n-dimensional pytorch Tensor.
    y is an n-dimensional pytorch Tensor.

    Return the sum of the element-wise product of the two tensors.
    """
    y = y.reshape(len(y), 1)
    return torch.sum(torch.mul(x, y))

In [224]:
tensor_sumproducts(torch.arange(3000), torch.arange(3000))

tensor(20236502250000)

In [5]:
A = np.array([[6, 5, 3, 1], [3, 6, 2, 2], [3, 4, 3, 1]])
B = np.array([[1.50, 1], [2, 2.5], [5, 4.5], [16, 17]])
A @ B

array([[50. , 49. ],
       [58.5, 61. ],
       [43.5, 43.5]])

$$55^5$$