# This is rework of [this article](https://machinelearningmastery.com/how-to-improve-performance-with-transfer-learning-for-deep-learning-neural-networks/) about transfer learning.

In [1]:
import numpy as np

In [30]:
np.random.seed(42)
x = np.random.randn(5, 4)
x

array([[ 0.49671415, -0.1382643 ,  0.64768854,  1.52302986],
       [-0.23415337, -0.23413696,  1.57921282,  0.76743473],
       [-0.46947439,  0.54256004, -0.46341769, -0.46572975],
       [ 0.24196227, -1.91328024, -1.72491783, -0.56228753],
       [-1.01283112,  0.31424733, -0.90802408, -1.4123037 ]])

In [31]:
x *= 0.5
x

array([[ 0.24835708, -0.06913215,  0.32384427,  0.76151493],
       [-0.11707669, -0.11706848,  0.78960641,  0.38371736],
       [-0.23473719,  0.27128002, -0.23170885, -0.23286488],
       [ 0.12098114, -0.95664012, -0.86245892, -0.28114376],
       [-0.50641556,  0.15712367, -0.45401204, -0.70615185]])

In [33]:
y = np.array([[-1,-2,-3,-4,-5],[6,7,8,9,0]])
y * y

array([[ 1,  4,  9, 16, 25],
       [36, 49, 64, 81,  0]])